name: Start jksb

on:
#   workflow_dispatch:
#   schedule:
#     - cron: '27 18,19,21 * * *'
  [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Start jksb Direct
      env:
#         mail_id: ${{secrets.mail_id}}
#         mail_pd: ${{secrets.mail_pd}}
#         processing_pool: ${{secrets.processing_pool}}
          jksb_username: '20212233'
      run: |
        python jksb.py
